### ISSUE TITLE
Angular 6 ?

### ISSUE THREAD

**Issue by Vbboi24** [frappe/gantt#105]
Has anyone got a Angular Compatible Version of this super Awesome Gantt Library ?

**Comment by sevenOneHero** [comment]
me too interested in knowing about this.

**Comment by diginikkari** [comment]
I was able to get it working with angular 6

```
import * as Gantt from 'frappe-gantt';
...

@ViewChild('gantt') ganttEl: ElementRef;
...

if (this.tasks.length) {
  this.gantt = new Gantt.default(this.ganttEl.nativeElement, this.tasks, {});
}
```

**Comment by Vbboi24** [comment]
Thanks, I only end up having a black block code by following the step

**Comment by adedip** [comment]
hi all, sorry for dumb question, I'm quite newbie on ng.
How do I select the id of the div to render the gantt to? I mean, I guess I should set nativeElement = '#gantt-div-id' right? but how?
Thanks

**Comment by adedip** [comment]
> hi all, sorry for dumb question, I'm quite newbie on ng.
> How do I select the id of the div to render the gantt to? I mean, I guess I should set nativeElement = '#gantt-div-id' right? but how?
> Thanks

nevermind found out... but still got "undefined" on this.ganttEl, ideas?

**Comment by victorldleon** [comment]
> Thanks, I only end up having a black block code by following the step

I was getting a black block too and I fixed it by copying the styles directly to my project.

**Comment by jcjobin** [comment]
FYI, I got it to work nicely with Angular 6 by the following:
HTML:
`<svg id="gantt" style="min-height: 100%"></svg>`

TS:
   ```
import { Gantt } from 'node_modules/frappe-gantt/src/index';

export class GanttComponent implements OnInit {
   gantt;
   ngOnInit() {
      this.gantt = new Gantt('#gantt', this.tasks);
   }
}
```

**Comment by nikilkumar9** [comment]
Anyone mind posting their full code showing how exactly they used this library in their Angular project? I am developing an Ionic App and am still having a lot of problems.

**Comment by zeddysoft** [comment]
i could not get this working with Angular 7, any ideas please

**Comment by zeddysoft** [comment]
> i could not get this working with Angular 7, any ideas please

got this working.

**Comment by thomas-lucas1985** [comment]
@zeddysoft How did you manage to get it working? I'm currently on Angular 8 and i'm not able to import Gantt as stated for version 6.

Any help would be much appreciated.

Thanks

**Comment by zeddysoft** [comment]
> @zeddysoft How did you manage to get it working? I'm currently on Angular 8 and i'm not able to import Gantt as stated for version 6.
> 
> Any help would be much appreciated.
> 
> Thanks

hi @thomas-lucas1985 , i followed https://github.com/frappe/gantt/issues/105#issuecomment-433412728, that was after i installed the frappe-gantt using NPM and referenced the css and js files in angular.json.

**Comment by thomas-lucas1985** [comment]
> > @zeddysoft How did you manage to get it working? I'm currently on Angular 8 and i'm not able to import Gantt as stated for version 6.
> > Any help would be much appreciated.
> > Thanks
> 
> hi @thomas-lucas1985 , i followed [#105 (comment)](https://github.com/frappe/gantt/issues/105#issuecomment-433412728), that was after i installed the frappe-gantt using NPM and referenced the css and js files in angular.json.

Many thanks. Got it running now.

**Comment by tobiashoeft** [comment]
> I was able to get it working with angular 6
>
> ```
> import * as Gantt from 'frappe-gantt';
> ...
>
> @ViewChild('gant
> ```

Hey for all how's get problems to get this running in Angular 8 and 9

A little hint is missing in that solution.

You must set the this.ganttEl in afterViewInit.

Like this:

`ngAfterViewInit(): void { const tasks = [ { id: "Task 1", name: "Redesign website", start: "2016-12-28", end: "2016-12-31", progress: 20, dependencies: "Task 2, Task 3" } ]; this.ganttEl = new Gantt.default(this.ganttEl.nativeElement, tasks, {}); }`


I get this runnig in angular.9.rc-13

**Comment by kenneth46k** [comment]
Hi, I'm new to ng. Using Angular 8 and trying to use above suggestions. But I'm not getting it clearly. Can someone help me to get it working.

**Comment by safwansamsudeen** [comment]
I'm closing this issue now as it doesn't seem to be a problem anymore.
