### ISSUE TITLE
Mistake of one day when resizing a task

### ISSUE THREAD

**Issue by Adioud** [frappe/gantt#73]
Hi,
First I would like to thank you for this library, simple and with beautifull.

Using it I just noticed this small issue: resizing a task there is one day mistake between the task as I draw graphycally, and the end date given by the "on_date_change" event.
For instance if I draw the task until de 1st january, the "on_date_change" will give task.end YYYY-01-02.

It would be a good thing if you can fix it in a next version,
Thank you one more time,
Adrien

**Comment by netchampfaris** [comment]
This should be fixed now. Try replicating on the latest build.

**Comment by Adioud** [comment]
Hi,
Well, the errors were caused by issues on my side (I used integer task id), I didn't notice it before,
So, I have cleaned this and it seems that I still have a gap of one day one the start date. Then end date is OK.

**Comment by sbaiti** [comment]
Hi , 
Are fixed this bug ,
@Adioud

**Comment by Adioud** [comment]
Hello,

As I said on the 1th jun I still have an error on the start date.
I see that sbaiti opened another issue for that: @netchampfaris you can close one of this two issues.

Thank,

**Comment by Anurag810** [comment]
@netchampfaris Have fixed this

**Comment by cdoug88** [comment]
Not sure if this is the same issue or not but...
I was having an issue where if I resized the task, the start date was actually off by one day and was saving that way to my DB. It was moving the start date backwards by one day. As a temporary fix until I can figure out how to fix it permanently, I have added the follow javascript:

`on_date_change: function(id, start, end) {
		function convert(str) {
		    var date = new Date(str),
		    mnth = ("0" + (date.getMonth() + 1)).slice(-2),
		    day = ("0" + date.getDate()).slice(-2);
		    return [date.getFullYear(), mnth, day].join("-");
		}
		var newEnd = convert(end);
		var newStartDate = start.setDate(start.getDate() + 1); // this is adding that day back
		var newStart = convert(newStartDate); // converting the date format to 2020-04-12 for db
		var newId = id.id;

	    $.ajax({
	       type:"post",
	       url:"_partials/update_date",
	       data:{id:newId,newstart:newStart,newend:newEnd},
	    });
}`

Hopefully this helps someone

**Comment by jlxcolo** [comment]
I found out the hard way that id can't be an int, which is kind of crazy... but this thread saved me. BIGINT in postgress gets auto quoted - which resolves the issue.

**Comment by safwansamsudeen** [comment]
It can now - fixed in #393.
