### ISSUE TITLE
Bars Disappear when clicked and dragged

### ISSUE THREAD

**Issue by toddgeist** [frappe/gantt#76]
Click and dragging a bar doesn't work on safari or chrome, mac osx

Here is a video
https://youtu.be/pTmHj60cF-k

Todd

**Comment by netchampfaris** [comment]
@toddgeist Hey, are you able to replicate this on latest build ?

**Comment by toddgeist** [comment]
looks like it is fixed

Thanks

**Comment by Carl-Gustaf** [comment]
This is still an issue for me. Same browser & platform as @toddgeist!
